

params_train:
    startfilter: 64
    start_kernel: 7
    mid_kernel: 3
    learning_rate: 1.0E-3
    batch_size: 32
    epochs: 250
    show: False
    stage_number: 3
    size_tminus: 1
    size_tplus: 1
    imagex: 64
    imagey: 64
    imagez: 8
    depth: {'depth_0': 12, 'depth_1': 24, 'depth_2': 16}
    reduction: 0.5


params_predict:
          n_tiles: [1,1,1]
          event_threshold: 0.999
          event_confidence: 0.9
          file_type: '*.tif'
      
          

trainclass:
     #Class can be NEATVollNet (ZYXT), NEATTResNet (YXT), NEATLRNet (TYXC) 
     training_class: NEATDenseVollNet
     # volume_config, lstm_config
     training_config: volume_config
     # Cellsplitdiamondcordxenopus.json, Cellsplitcordxenopus.json
     cord_json: 'cord.json'
     categories_json: 'catagories.json'

defaults:
   - files_oneat: oneat_files
   - paths_oneat: oneat_paths_jean_zay
   - _self_     
