params:
   
    depth: 4
    epochs: 200
    learning_rate: 0.0003
    batch_size: 2
    patch_x: 128
    patch_y: 128
    patch_z: 16
    kern_size: 3
    n_patches_per_image: 32
    n_rays: 96
    startfilter: 32
    erosion_iterations: 5
    use_gpu_opencl: False
    generate_npz: False
    backbone: 'unet'
    load_data_sequence: False
    validation_split: 0.01
    n_channel_in: 1
    train_unet: True
    train_star: False
    train_loss: 'mae'
    file_type: '*.tif'
    min_size: 1
    min_size_mask: 10
    max_size: 1000000
    n_tiles: [4,4,4]
    axes: 'ZYX'
    dounet: False
    seedpool: False 
    slice_merge: False
    UseProbability: True 
    donormalize: True 
    ExpandLabels: False
    diameter_cellpose: 34.6
    stitch_threshold: 0.5
    channel_membrane: 0
    channel_nuclei: 1
    flow_threshold: 0.4 
    cellprob_threshold: 0.0
    anisotropy: None
    cellpose_model: True
    custom_cellpose_model: False
    gpu: False
     
    

defaults:
   - files_vollseg: vollseg_files
   - paths_vollseg: vollseg_paths_jean_zay
   - _self_ 
       
