params:
   
    depth: 3
    epochs: 200
    learning_rate: 0.0003
    batch_size: 16
    patch_x: 128
    patch_y: 128
    patch_z: 16    
    kern_size: 3
    n_patches_per_image: 128
    n_rays: 96
    startfilter: 32
    erosion_iterations: 0
    use_gpu_opencl: False
    generate_npz: True
    backbone: 'unet'
    load_data_sequence: False
    validation_split: 0.01
    n_channel_in: 1
    train_unet: True
    train_seed_unet: False
    train_star: False
    train_loss: 'mae'
    file_type: '*.tif'
    min_size: 1
    min_size_mask: 10
    max_size: 1000000
    n_tiles: [4,4,4]
    axes: 'ZYX'
    dounet: True
    seedpool: False 
    slice_merge: False
    UseProbability: True 
    donormalize: True 
    ExpandLabels: False
    diameter_cellpose: 34.6
    stitch_threshold: 0.5
    channel_membrane: 0
    channel_nuclei: 1
    flow_threshold: 0.4 
    cellprob_threshold: 0.0
    cellpose_model: True
    custom_cellpose_model: False
    gpu: False
    do_3D: False
     
aug_params:
       

        gauss_filter_size: 0
        #choices for augmentation below are 1 or 2 or None
        flip_axis: 1
        shift_axis: 1
        zoom_axis: 1
        #shift range can be between -1 and 1 (-1 and 1 will translate the pixels completely out), zoom range > 0
        shift_range: 0.2 
        zoom_range: 2
        rotate_axis: 1
        rotation_angles: [20, 40, 60, 90, 120, 160] 
        pattern : [".tif", ".TIFF", ".TIF", ".png"] 
        sigma : 10
        mean : 0
        alpha_affine : 1.8
        alpha : 3
        distribution : 'Both'

defaults:
   - files_vollseg: vollseg_files
   - paths_vollseg: vollseg_paths_jean_zay
   - _self_ 
       
