

params_train:
    startfilter: 16
    start_kernel: 7
    mid_kernel: 3
    depth: 29
    learning_rate: 1.0E-3
    batch_size: 2
    epochs: 250
    show: False
    stage_number: 3
    size_tminus: 1
    size_tplus: 1
    imagex: 64
    imagey: 64
    imagez: 8
    nboxes: 1
    pure_lstm: False
    normalizeimage: True



params_predict:
          n_tiles: (1,1,1)
          event_threshold: 0.9999
          event_confidence: 0.9
          downsamplefactor: 1
          start_project_mid: 4
          end_project_mid: 1
          normalize: True
          nms_function: 'iou'
          file_type: '*.tif'
          remove_markers: False
          nms_space: 10
          nms_time: 2
          volume: True

trainclass:
     #Class can be NEATVollNet (ZYXT), NEATTResNet (YXT), NEATLRNet (TYXC) 
     training_class: NEATVollNet
     # volume_config, lstm_config
     training_config: volume_config
     # Cellsplitdiamondcordxenopus.json, Cellsplitcordxenopus.json
     cord_json: 'Cellsplitdiamondcordxenopus.json'
     categories_json: 'Cellsplitcategoriesxenopus.json'

defaults:
   - files_oneat: oneat_files
   - paths_oneat: oneat_paths_ovh
   - _self_     
