

params:
    startfilter: 48
    start_kernel: 7
    mid_kernel: 3
    depth: 56
    learning_rate: 1.0E-3
    batch_size: 20
    epochs: 250
    show: False
    stage_number: 3
    size_tminus: 1
    size_tplus: 1
    imagex: 64
    imagey: 64
    imagez: 8
    nboxes: 1
    pure_lstm: False
    cord_json: 'Cellsplitdiamondcordxenopus.json'

trainclass:
     training_class: NEATEynamic
     training_config: diamond_config

defaults:
   - files_oneat: oneat_files
   - paths_oneat: oneat_paths_ovh
   - _self_     