#!/bin/bash

module load anaconda-py3
conda activate naparienv

set -x # activating echo of

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/linkhome/rech/gengoq01/uzj81mi/.conda/envs/naparienv/lib/
echo $LD_LIBRARY_PATH

python  /gpfswork/rech/jsy/uzj81mi/Mari_Scripts_Server/color_tracks.py
